### ISSUE TITLE
Some enchancment

### ISSUE THREAD

**Issue by ktaranov** [LitKnd/BabbyNames#1]
Hy, Kendar!

Great thanks for your sample base and also for amazing free courses (https://sqlworkbooks.com) and ,certainly, your awesome blog.

I want to take some enhancement especially for markdown syntax, do you need some contribution or not interested for this project?

**Comment by LitKnd** [comment]
I'm totally open to contributions. I'm not sure where you want to make the markdown syntax enhancements, but I'm intrigued!

**Comment by ktaranov** [comment]
https://github.com/LitKnd/BabbyNames/pull/2
